---
title: "Setting up flexible toy model"
author: "Claire Powers"
date: "2024-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up
```{r packages_functions, message=FALSE, warning=FALSE}
rm(list=ls()) 
library(tidyverse)

source("Code/R/survival_fun.R")
source("Code/R/logit2prob.R")
source("Code/R/growth_fun.R")
source("Code/R/seednum_fun.R")
source("Code/R/SG_mx_fun.R")
source("Code/R/subpop_mx_fun.R")
theme_set(theme_bw(base_size=14))
cols = c(sdlg="springgreen4",juv="slateblue3",flrg="magenta3")
```

## Set params
```{r params}
# params for base matrix
sizes = c(sdlg=1,juv=5,flrg=10)
P.flr = 0.8 # Probability of flowering
P.germ = 0.01 # Probability of seeds germinating
surv_params = list(sizes=sizes,
                   survival.rates = c(sdlg = 0.2,juv=0.75,flrg=0.95),
                   S_c = c(-0.02,-0.01,0.0),
                   S_d = c(-0.08,-0.05,-0.03),
                   clim=0,S.asp.mag=0,S.asp.effect=0)

surv.rates = survival_fun(sizes = surv_params$sizes,
                          survival.rates = surv_params$survival.rates,
                          S_c = surv_params$S_c,
                          S_d = surv_params$S_d)

growth_params = list(sizes=sizes,
                     growth.rates = c(sdlg=0.1,juv=0.45),
                     G_c = c(0.001,0.001),
                     G_d = c(-0.0035,-0.0025))

growth.rates = growth_fun(sizes = growth_params$sizes,
                          growth.rates = growth_params$growth.rates,
                          G_c = growth_params$G_c,
                          G_d = growth_params$G_d)

sg_mx = mx = sg_mx_fun(surv.rates = surv.rates,growth.rates = growth.rates)
seed.optim <- stats::optim(par = 100, fn = seednum_fun, method = "L-BFGS-B", lower=0, upper=10000,control = list(factr = 1e-15))
seeds <- round(seed.optim$par)
mx[1,3] <- as.numeric(surv.rates["flrg"]*P.flr*seeds*P.germ)
Re(eigen(mx)$values[1])
```

## Plot S and G against regional climate vals to check curves
```{r determine.surv.params}

#### Survival plots ####
S.df = data.frame(clim=seq(-5,5,by=0.01),sdlg=NA,juv=NA,flrg=NA) 

for(i in 1:nrow(S.df)){
  
  survs.i = survival_fun(sizes = surv_params$survival.rates,
                         survival.rates = surv_params$survival.rates,
                         clim=S.df$clim[i],
                         S_c = surv_params$S_c,
                         S_d = surv_params$S_d)
  S.df[i,c("sdlg","juv","flrg")] = survs.i
}

S.plot.df = pivot_longer(S.df,cols = c(sdlg,juv,flrg),names_to = "stage",values_to = "surv")

surv = ggplot(S.plot.df,aes(x=clim,y=surv,color=stage))+
  geom_vline(xintercept = 0)+
  geom_hline(yintercept = 0) + 
  geom_line(linewidth=2) + 
 # facet_wrap(~stage,ncol=1) +
  scale_color_manual(values=cols)+
  labs(title="survival")
#surv
######

#### Growth plots ####

G.df = data.frame(clim=seq(-5,5,by=0.1),sdlg=NA,juv=NA,flrg=NA) 

for(i in 1:nrow(G.df)){
  
  grows.i = growth_fun(sizes = growth_params$sizes,
                       growth.rates = growth_params$growth.rates,
                       clim = G.df$clim[i],
                       G_c = growth_params$G_c,
                       G_d = growth_params$G_d)
  G.df[i,c("sdlg","juv")] = grows.i

  
    
}

G.plot.df = pivot_longer(G.df,cols = c(sdlg,juv),names_to = "stage",values_to = "grow")

grow = ggplot(G.plot.df,aes(x=clim,y=grow,color=stage))+
  geom_hline(yintercept = 0)+
  geom_vline(xintercept = 0)+
  geom_line(linewidth=2)+
  scale_color_manual(values=cols)+
  #facet_wrap(~stage,ncol=1)+
  labs(title="growth")
#grow
#####

cowplot::plot_grid(surv,grow,ncol=1)

# rm(G.plot.df,grows.i,i,G.df,survs.i,S.plot.df,S.df)
```

## Build G matrix with flexibilty around number of (identical) subpopulations
```{r build pop.mx}
n.subpops = 3
surv_params$clim=0;surv_params$S.asp.effect=0;surv_params$S.asp.mag=0
growth_params$clim=0;growth_params$G.asp.effect=0;growth_params$G.asp.mag=0

# large zero matrix
pop_mx = matrix(data = 0,ncol = 3*n.subpops,nrow=3*n.subpops)

for(i in 1:n.subpops){
  
  start.cell = start.cells[i]
  
  # get subpop i mx
  m_i = subpop_mx_fun(surv_params = surv_params,growth_params = growth_params,seeds=seeds)$subpop_mx
  Re(eigen(m_i)$values[1])
  
  # put into g.mx
  pop_mx[(0+start.cell):(2+start.cell),(0+start.cell):(2+start.cell)]=m_i
  
  # remove to avoid mistakes
  rm(m_i,i,start.cell)
}
Re(eigen(pop_mx)$values[1])
```

